apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flaskapp-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: psrv3/kodekloud_jenkins_flask_app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
